# Generated by Django 3.1.6 on 2021-02-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='product.ProductCategory'),
        ),
        migrations.DeleteModel(
            name='ProductProductCategory',
        ),
    ]
