# Generated by Django 3.1.6 on 2021-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210224_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_year',
            field=models.CharField(max_length=10),
        ),
    ]
