# Generated by Django 3.1.6 on 2021-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210224_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
